import type { NextPage } from "next";
import Head from "next/head";
import Header from "@/components/Header";
import TodoList from "@/components/TodoList";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="p-20 w-full flex justify-center">
        <TodoList />
      </main>
    </div>
  );
};

export default Home;
